/*
	@File		ModeHeader.sp
	@Usage		The main methodmap for a mode, do not edit this file at any cost!!
*/

#if defined _FM_ModeHeader_SP
	#endinput
#endif

#if !defined THIS_MODE_TYPE_NAME
	#endinput
#endif

#if !defined THIS_MODE_FWD_FLAGS
	#endinput
#endif

#if !defined THIS_MODE_FILE_NAME
	#endinput
#endif

#define _FM_ModeHeader_SP

FUNMODES_CREATE_METHODMAP(THIS_MODE_TYPE_NAME)
{
	public static void OnPluginStart()
	{
		CALL_MODE_FORWARD0(OnPluginStart, THIS_MODE_FILE_NAME);

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnPluginStart();
	#endif
	}

	public static void OnPluginEnd()
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnPluginEnd)
		CALL_MODE_FORWARD0(OnPluginEnd, THIS_MODE_FILE_NAME);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnPluginEnd();
	#endif
	}

	public static void OnMapStart()
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnMapStart)
		CALL_MODE_FORWARD0(OnMapStart, THIS_MODE_FILE_NAME);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnMapStart();
	#endif
	}

	public static void OnMapEnd()
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnMapEnd)
		CALL_MODE_FORWARD0(OnMapEnd, THIS_MODE_FILE_NAME);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnMapEnd();
	#endif
	}

	public static void OnClientPutInServer(int client)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnClientPutInServer)
		CALL_MODE_FORWARD1(OnClientPutInServer, THIS_MODE_FILE_NAME, client);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnClientPutInServer(client);
	#endif
	}

	public static void OnClientDisconnect(int client)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnClientDisconnect)
		CALL_MODE_FORWARD1(OnClientDisconnect, THIS_MODE_FILE_NAME, client);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnClientDisconnect(client);
	#endif
	}

	public static void ZR_OnClientInfected(int client)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(ZR_OnClientInfected)
		CALL_MODE_FORWARD1(ZR_OnClientInfected, THIS_MODE_FILE_NAME, client);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.ZR_OnClientInfected(client);
	#endif
	}

	public static void Event_RoundStart()
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(Event_RoundStart)
		CALL_MODE_FORWARD0(Event_RoundStart, THIS_MODE_FILE_NAME);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.Event_RoundStart();
	#endif
	}

	public static void Event_RoundEnd()
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(Event_RoundEnd)
		CALL_MODE_FORWARD0(Event_RoundEnd, THIS_MODE_FILE_NAME);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.Event_RoundEnd();
	#endif
	}

	public static void Event_PlayerSpawn(int client)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(Event_PlayerSpawn)
		CALL_MODE_FORWARD1(Event_PlayerSpawn, THIS_MODE_FILE_NAME, client);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.Event_PlayerSpawn(client);
	#endif
	}

	public static void Event_PlayerTeam(Event event)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(Event_PlayerTeam)
		CALL_MODE_FORWARD1(Event_PlayerTeam, THIS_MODE_FILE_NAME, event);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.Event_PlayerTeam(event);
	#endif
	}

	public static void Event_PlayerDeath(int client)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(Event_PlayerDeath)
		CALL_MODE_FORWARD1(Event_PlayerDeath, THIS_MODE_FILE_NAME, client);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.Event_PlayerDeath(client);
	#endif
	}

	public static void OnTakeDamagePost(int victim, int attacker, float damage)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnTakeDamagePost)
		CALL_MODE_FORWARD3(OnTakeDamagePost, THIS_MODE_FILE_NAME, victim, attacker, damage);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnTakeDamagePost(victim, attacker, damage);
	#endif
	}

	public static void OnTakeDamage(int victim, int attacker, float damage, Action &result)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnTakeDamage)
		CALL_MODE_FORWARD4(OnTakeDamage, THIS_MODE_FILE_NAME, victim, attacker, damage, result);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnTakeDamage(victim, attacker, damage, result);
	#endif
	}

	public static void OnWeaponEquip(int client, int weapon, Action &result)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnWeaponEquip)
		CALL_MODE_FORWARD3(OnWeaponEquip, THIS_MODE_FILE_NAME, client, weapon, result);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnWeaponEquip(client, weapon, result);
	#endif
	}

	public static void OnPlayerRunCmdPost(int client, int buttons, int impulse)
	{
	#if THIS_MODE_FWD_FLAGS & FWD_FLAG(OnPlayerRunCmdPost)
		CALL_MODE_FORWARD3(OnPlayerRunCmdPost, THIS_MODE_FILE_NAME, client, buttons, impulse);
	#endif

	#if defined LAST_MODE_TYPE
		LAST_MODE_TYPE.OnPlayerRunCmdPost(client, buttons, impulse);
	#endif
	}
}

#undef _FM_ModeHeader_SP // end _FM_ModeHeader_SP
